"""
Guide to Finding Giuffre v. Maxwell on Leagle
"""

print("=" * 70)
print("HOW TO FIND GIUFFRE v. MAXWELL ON LEAGLE")
print("=" * 70)

print("\nCASE DETAILS:")
print("-" * 50)
print("Case: Giuffre v. Maxwell")
print("Citation: 146 F.4th 165")
print("Court: 2nd Circuit Court of Appeals")
print("Decision Date: July 23, 2025")
print("Docket: 24-182-cv(L), 24-203-cv(CON)")

print("\nNAVIGATION STEPS FOR LEAGLE:")
print("-" * 50)
print("1. Go to: https://www.leagle.com/decisions")
print("")
print("2. Use the search options:")
print("   - Search by case name: 'Giuffre v. Maxwell'")
print("   - OR search by citation: '146 F.4th 165'")
print("   - OR browse by court and date")
print("")
print("3. If browsing by court:")
print("   a. Select 'Federal Courts'")
print("   b. Select 'Second Circuit'")
print("   c. Navigate to 2025 decisions")
print("   d. Look for July 2025")
print("")
print("4. Alternative - use Google search:")
print("   'site:leagle.com Giuffre v. Maxwell 2025'")

print("\nPOTENTIAL ISSUES:")
print("-" * 50)
print("1. Too Recent:")
print("   - July 2025 case may not be published yet")
print("   - Federal Reporter has publication delays")
print("   - Leagle might not have it yet")
print("")
print("2. Citation Format:")
print("   - Might appear as '2025 WL XXXXXXXX' first")
print("   - F.4th citation comes later")
print("")
print("3. Alternative Citations:")
print("   - Check for: '2025 U.S. App. LEXIS XXXXX'")
print("   - Or docket number citations")

print("\nIF NOT FOUND ON LEAGLE:")
print("-" * 50)
print("1. Check the court website:")
print("   - https://www.ca2.uscourts.gov/")
print("   - Recent opinions are posted first")
print("")
print("2. Check PACER:")
print("   - Free for opinions older than 90 days")
print("   - Search by docket: 24-182-cv(L)")
print("")
print("3. Google Scholar:")
print("   - Most likely to have recent cases")
print("   - Search: 'Giuffre v. Maxwell 2nd Cir 2025'")

print("\n" + "=" * 70)
print("NOTE:")
print("-" * 50)
print("I cannot directly navigate websites, but these steps")
print("should help you locate the case if it's available.")
print("=" * 70)
